---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-runner
  namespace: uptime-kuma
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: uptime-kuma
  name: backup-runner-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-runner-rolebinding
  namespace: uptime-kuma
subjects:
- kind: ServiceAccount
  name: backup-runner
  namespace: uptime-kuma
roleRef:
  kind: Role
  name: backup-runner-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kuma-backup-cron
  namespace: uptime-kuma
spec:
  schedule: "0 19 * * *" # UTC 時間的 19:00，即台灣時間 3:00
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: backup-runner
          containers:
          - name: trigger-backup
            image: bitnami/kubectl:latest
            command:
              - /bin/bash
              - -c
              - |
                kubectl exec -n uptime-kuma -c kuma-backup uptime-kuma-0 -- /bin/bash -c "
                tar -czf /tmp/backup.tar.gz -C /data .
                oci os object put -bn uptime-kuma-backup --file /tmp/backup.tar.gz --name backup.tar.gz
                rm -f /tmp/backup.tar.gz
                "
          restartPolicy: Never
