apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  replicas: 1
  serviceName: uptime-kuma-service
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        # 主容器：Uptime Kuma
        - name: uptime-kuma
          image: louislam/uptime-kuma:1.23.15
          env:
            - name: UPTIME_KUMA_PORT
              value: "3001"
            - name: PORT
              value: "3001"
          ports:
            - name: uptime-kuma
              containerPort: 3001
              protocol: TCP
          volumeMounts:
            - name: kuma-data
              mountPath: /app/data

        # Sidecar 容器：備份到 Oracle Cloud Object Storage
        - name: kuma-backup
          image: ghcr.io/oracle/oci-cli:latest
          command: ["/bin/bash", "-c", "sleep infinity"]
          volumeMounts:
            - name: kuma-data
              mountPath: /data
            - name: oci-secret
              mountPath: /secrets
              readOnly: true
          env:
            - name: OCI_CLI_CONFIG_FILE
              value: /secrets/config
            - name: OCI_CLI_KEY_FILE
              value: /secrets/oci_api_key.pem
            - name: OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING
              value: "True"

      volumes:
        - name: oci-secret
          secret:
            secretName: oci-secret

  volumeClaimTemplates:
    - metadata:
        name: kuma-data
      spec:
        accessModes: ["ReadWriteOnce"]
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
